// AUTH ACTIONS OR LOGIN ACTIONS
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// SET PASSWORD ACTIONS
export const SET_PASSWORD_START = 'SET_PASSWORD_START';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';

// VENDOR ACCEPT ACTIONS
export const VENDOR_ACCEPT_START = 'VENDOR_ACCEPT_START'
export const VENDOR_ACCEPT_SUCCESS = 'VENDOR_ACCEPT_SUCCESS'
export const VENDOR_ACCEPT_FAIL = 'VENDOR_ACCEPT_FAIL'

// VENDOR REJECT ACTIONS
export const VENDOR_REJECT_START = 'VENDOR_REJECT_START'
export const VENDOR_REJECT_SUCCESS = 'VENDOR_REJECT_SUCCESS'
export const VENDOR_REJECT_FAIL = 'VENDOR_REJECT_FAIL'


export const FORGOT_PASSWORD_START_EMAIL = 'FORGOT_PASSWORD_START_EMAIL';
export const FORGOT_PASSWORD_SUCCESS_EMAIL = 'FORGOT_PASSWORD_SUCCESS_EMAIL';
export const FORGOT_PASSWORD_FAIL_EMAIL = 'FORGOT_PASSWORD_FAIL_EMAIL';

export const FORGOT_PASSWORD_START_OTP = 'FORGOT_PASSWORD_START_OTP';
export const FORGOT_PASSWORD_SUCCESS_OTP = 'FORGOT_PASSWORD_SUCCESS_OTP';
export const FORGOT_PASSWORD_FAIL_OTP = 'FORGOT_PASSWORD_FAIL_OTP';

export const LOGOUT = 'LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// COMMON ACTIONS
export const PAYNOW_START = 'PAYNOW_START';
export const PAYNOW_SUCCESS = 'PAYNOW_SUCCESS';
export const PAYNOW_FAIL = 'PAYNOW_FAIL';

export const SEACRHING_START = 'SEACRHING_START';
export const SEACRHING_SUCCESS = 'SEACRHING_SUCCESS';
export const SEACRHING_FAIL = 'SEACRHING_FAIL';

export const FEEDBACK_RATING_START = 'FEEDBACK_RATING_START';
export const FEEDBACK_RATING_SUCCESS = 'FEEDBACK_RATING_SUCCESS';
export const FEEDBACK_RATING_FAIL = 'FEEDBACK_RATING_FAIL';

export const RESET_FEEBACK_RATING = 'RESET_FEEBACK_RATING';

export const FETCH_BELL_NOTIFICATIONS_START = 'FETCH_BELL_NOTIFICATIONS_START';
export const FETCH_BELL_NOTIFICATIONS_SUCCESS = 'FETCH_BELL_NOTIFICATIONS_SUCCESS';
export const FETCH_BELL_NOTIFICATIONS_FAIL = 'FETCH_BELL_NOTIFICATIONS_FAIL';

export const FETCH_UNSEEN_BELL_NOTIFICATIONS_START = 'FETCH_UNSEEN_BELL_NOTIFICATIONS_START';
export const FETCH_UNSEEN_BELL_NOTIFICATIONS_SUCCESS = 'FETCH_UNSEEN_BELL_NOTIFICATIONS_SUCCESS';
export const FETCH_UNSEEN_BELL_NOTIFICATIONS_FAIL = 'FETCH_UNSEEN_BELL_NOTIFICATIONS_FAIL';

export const UPDATE_UNSEEN_BELL_NOTIFICATIONS_START = 'UPDATE_UNSEEN_BELL_NOTIFICATIONS_START';
export const UPDATE_UNSEEN_BELL_NOTIFICATIONS_SUCCESS = 'UPDATE_UNSEEN_BELL_NOTIFICATIONS_SUCCESS';
export const UPDATE_UNSEEN_BELL_NOTIFICATIONS_FAIL = 'UPDATE_UNSEEN_BELL_NOTIFICATIONS_FAIL';

// DASHBOARD ACTIONS
export const FETCH_USER_VM_START = 'FETCH_USER_VM_START';
export const FETCH_USER_VM_SUCCESS = 'FETCH_USER_VM_SUCCESS';
export const FETCH_USER_VM_FAIL = 'FETCH_USER_VM_FAIL';

export const UPDATES_EXISTING_VM_START = 'UPDATES_EXISTING_VM_START';
export const UPDATES_EXISTING_VM_SUCCESS = 'UPDATES_EXISTING_VM_SUCCESS';
export const UPDATES_EXISTING_VM_FAIL = 'UPDATES_EXISTING_VM_FAIL';

export const VM_INSTANCES = 'VM_INSTANCES';
export const VM_SERVICES_STATUS_START = 'VM_SERVICES_STATUS_START';
export const VM_SERVICES_STATUS_SUCCESS = 'VM_SERVICES_STATUS_SUCCESS';
export const VM_SERVICES_STATUS_FAIL = 'VM_SERVICES_STATUS_FAIL';

export const OUTSTANDING_BILLING_START = 'OUTSTANDING_BILLING_START'
export const OUTSTANDING_BILLING_SUCCESS = 'OUTSTANDING_BILLING_SUCCESS'
export const OUTSTANDING_BILLING_FAIL = 'OUTSTANDING_BILLING_FAIL'

export const TICKETS_COUNT_START = 'TICKETS_COUNT_START';
export const TICKETS_COUNT_SUCCESS = 'TICKETS_COUNT_SUCCESS';
export const TICKETS_COUNT_FAIL = 'TICKETS_COUNT_FAIL';

export const DASHBOARD_TAGS_START = 'DASHBOARD_TAGS_START';
export const DASHBOARD_TAGS_SUCCESS = 'DASHBOARD_TAGS_SUCCESS';
export const DASHBOARD_TAGS_FAIL = 'DASHBOARD_TAGS_FAIL';


// Adding tags 
export const ADDING_TAGS_START = 'ADDING_TAGS_START';
export const ADDING_TAGS_SUCCESS = 'ADDING_TAGS_SUCCESS';
export const ADDING_TAGS_FAIL = 'ADDING_TAGS_FAIL';

// Edit Instance task
export const VM_INSTANCE_EDITING_START = 'VM_INSTANCE_EDITING_START';
export const VM_INSTANCE_EDITING_SUCCESS = 'VM_INSTANCE_EDITING_SUCCESS';
export const VM_INSTANCE_EDITING_FAIL = 'VM_INSTANCE_EDITING_FAIL';


// Sheduled task
export const VM_SHEDULED_TASK_START = 'VM_SHEDULED_TASK_START';
export const VM_SHEDULED_TASK_SUCCESS = 'VM_SHEDULED_TASK_SUCCESS';
export const VM_SHEDULED_TASK_FAIL = 'VM_SHEDULED_TASK_FAIL';


// Reboot task
export const VM_REBOOT_START = 'VM_REBOOT_START';
export const VM_REBOOT_SUCCESS = 'VM_REBOOT_SUCCESS';
export const VM_REBOOT_FAIL = 'VM_REBOOT_FAIL';

// ASSIGN VENDOR FROM DASHBOARD
export const ASSIGNED_VENDOR_LIST_START = 'ASSIGNED_VENDOR_LIST_START';
export const ASSIGNED_VENDOR_LIST_SUCCESS = 'ASSIGNED_VENDOR_LIST_SUCCESS';
export const ASSIGNED_VENDOR_LIST_FAIL = 'ASSIGNED_VENDOR_LIST_FAIL';

// ASSIGN VENDOR FROM DASHBOARD
export const UPDATE_CUSTOMER_VM_VENDOR_START = 'UPDATE_CUSTOMER_VM_VENDOR_START';
export const UPDATE_CUSTOMER_VM_VENDOR_SUCCESS = 'UPDATE_CUSTOMER_VM_VENDOR_SUCCESS';
export const UPDATE_CUSTOMER_VM_VENDOR_FAIL = 'UPDATE_CUSTOMER_VM_VENDOR_FAIL';

// SEACRH VENDOR TO BE ASSINGED DASHBOARD
export const SEARCH_VENDOR_NAME_START = 'SEARCH_VENDOR_NAME_START';
export const SEARCH_VENDOR_NAME_SUCCESS = 'SEARCH_VENDOR_NAME_SUCCESS';
export const SEARCH_VENDOR_NAME_FAIL = 'SEARCH_VENDOR_NAME_FAIL';

// SEACRH VENDOR TO BE ASSINGED DASHBOARD
export const FETCH_VENDORS_LISTS_START = 'FETCH_VENDORS_LISTS_START';
export const FETCH_VENDORS_LISTS_SUCCESS = 'FETCH_VENDORS_LISTS_SUCCESS';
export const FETCH_VENDORS_LISTS_FAIL = 'FETCH_VENDORS_LISTS_FAIL';

// ASSIGN THE VMS VENDOR TO BE ASSINGED DASHBOARD
export const ASSIGNVM_VENDORS_START = 'ASSIGNVM_VENDORS_START';
export const ASSIGNVM_VENDORS_SUCCESS = 'ASSIGNVM_VENDORS_SUCCESS';
export const ASSIGNVM_VENDORS_FAIL = 'ASSIGNVM_VENDORS_FAIL';

// REMOVE VENDOR FROM DASHBOARD
export const REMOVE_VENDOR_START = 'REMOVE_VENDOR_START';
export const REMOVE_VENDOR_SUCCESS = 'REMOVE_VENDOR_SUCCESS';
export const REMOVE_VENDOR_FAIL = 'REMOVE_VENDOR_FAIL';

// REMOVE VENDOR FROM DASHBOARD
export const ADD_VENDOR_START = 'ADD_VENDOR_START';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_FAIL = 'ADD_VENDOR_FAIL';


// TICKETS ACTIONS
export const TICKETS_START = 'TICKETS_START';
export const TICKETS_SUCCESS = 'TICKETS_SUCCESS';
export const TICKETS_FAIL = 'TICKETS_FAIL';

export const ADDING_NEW_TICKETS_START = 'ADDING_NEW_TICKETS_START';
export const ADDING_NEW_TICKETS_SUCCESS = 'ADDING_NEW_TICKETS_SUCCESS';
export const ADDING_NEW_TICKETS_FAIL = 'ADDING_NEW_TICKETS_FAIL';

export const FETCH_UPDATES_TICKETS_MESSAGE_START = 'FETCH_UPDATES_TICKETS_MESSAGE_START';
export const FETCH_UPDATES_TICKETS_MESSAGE_SUCCESS = 'FETCH_UPDATES_TICKETS_MESSAGE_SUCCESS';
export const FETCH_UPDATES_TICKETS_MESSAGE_FAIL = 'FETCH_UPDATES_TICKETS_MESSAGE_FAIL';

export const UPDATING_TICKETS_START = 'UPDATING_TICKETS_START';
export const UPDATING_TICKETS_SUCCESS = 'UPDATING_TICKETS_SUCCESS';
export const UPDATING_TICKETS_FAIL = 'UPDATING_TICKETS_FAIL';

export const OUTSTANDING_SUCCESS = 'OUTSTANDING_SUCCESS';

// USER ACTIONS
export const SUB_USERS_LIST_START = 'SUB_USERS_LIST_START';
export const SUB_USERS_LIST_SUCCESS = 'SUB_USERS_LIST_SUCCESS';
export const SUB_USERS_LIST_FAIL = 'SUB_USERS_LIST_FAIL';

// adding sub users
export const ADD_SUB_USERS_START = 'ADD_SUB_USERS_START';
export const ADD_SUB_USERS_SUCCESS = 'ADD_SUB_USERS_SUCCESS';
export const ADD_SUB_USERS_FAIL = 'ADD_SUB_USERS_FAIL';

// verifying sub users mail
export const VERIFY_SUB_USER_MAIL_START = 'VERIFY_SUB_USER_MAIL_START';
export const VERIFY_SUB_USER_MAIL_SUCCESS = 'VERIFY_SUB_USER_MAIL_SUCCESS';
export const VERIFY_SUB_USER_MAIL_FAIL = 'VERIFY_SUB_USER_MAIL_FAIL';

// editing sub users
export const EDIT_SUB_USERS_START = 'EDIT_SUB_USERS_START';
export const EDIT_SUB_USERS_SUCCESS = 'EDIT_SUB_USERS_SUCCESS';
export const EDIT_SUB_USERS_FAIL = 'EDIT_SUB_USERS_FAIL';

// Update sub users
export const UPDATE_SUB_USERS_START = 'UPDATE_SUB_USERS_START';
export const UPDATE_SUB_USERS_SUCCESS = 'UPDATE_SUB_USERS_SUCCESS';
export const UPDATE_SUB_USERS_FAIL = 'UPDATE_SUB_USERS_FAIL';

// changing password for the sub users
export const CHANGE_PASSWORD_SUB_USERS_START = 'CHANGE_PASSWORD_SUB_USERS_START';
export const CHANGE_PASSWORD_SUB_USERS_SUCCESS = 'CHANGE_PASSWORD_SUB_USERS_SUCCESS';
export const CHANGE_PASSWORD_SUB_USERS_FAIL = 'CHANGE_PASSWORD_SUB_USERS_FAIL';

// logs for the sub users
export const FETCH_LOGS_SUB_USERS_START = 'FETCH_LOGS_SUB_USERS_START';
export const FETCH_LOGS_SUB_USERS_SUCCESS = 'FETCH_LOGS_SUB_USERS_SUCCESS';
export const FETCH_LOGS_SUB_USERS_FAIL = 'FETCH_LOGS_SUB_USERS_FAIL';

// deleting sub users
export const DELETE_SUB_USERS_START = 'DELETE_SUB_USERS_START';
export const DELETE_SUB_USERS_SUCCESS = 'DELETE_SUB_USERS_SUCCESS';
export const DELETE_SUB_USERS_FAIL = 'DELETE_SUB_USERS_FAIL';

// assinging the instances to the sub users
export const ASSIGN_INSTANCES_START = 'ASSIGN_INSTANCES_START';
export const ASSIGN_INSTANCES_SUCCESS = 'ASSIGN_INSTANCES_SUCCESS';
export const ASSIGN_INSTANCES_FAIL = 'ASSIGN_INSTANCES_FAIL';

// fetching roles to the sub users
export const FETCH_ROLES_START = 'FETCH_ROLES_START';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAIL = 'FETCH_ROLES_FAIL';


// assinging roles to the sub users
export const ASSIGN_ROLES_START = 'ASSIGN_ROLES_START';
export const ASSIGN_ROLES_SUCCESS = 'ASSIGN_ROLES_SUCCESS';
export const ASSIGN_ROLES_FAIL = 'ASSIGN_ROLES_FAIL';

// fetching instnaces to the sub users
export const FETCH_INSTANCES_START = 'FETCH_INSTANCES_START';
export const FETCH_INSTANCES_SUCCESS = 'FETCH_INSTANCES_SUCCESS';
export const FETCH_INSTANCES_FAIL = 'FETCH_INSTANCES_FAIL';

// INSTANCE ACTIONS
export const INSTANCES_LISTS_START = 'INSTANCES_LISTS_START';
export const INSTANCES_LISTS_SUCCESS = 'INSTANCES_LISTS_SUCCESS';
export const INSTANCES_LISTS_FAIL = 'INSTANCES_LISTS_FAIL';

export const INSTANCE_NOTIFICATIONS_START = 'INSTANCE_NOTIFICATIONS_START';
export const INSTANCE_NOTIFICATIONS_SUCCESS = 'INSTANCE_NOTIFICATIONS_SUCCESS';
export const INSTANCE_NOTIFICATIONS_FAIL = 'INSTANCE_NOTIFICATIONS_FAIL';

export const INSTANCE_STATUS_START = 'INSTANCE_STATUS_START';
export const INSTANCE_STATUS_SUCCESS = 'INSTANCE_STATUS_SUCCESS';
export const INSTANCE_STATUS_FAIL = 'INSTANCE_STATUS_FAIL';

// CLOUD CONNECT ACTIONS
export const CLOUD_CONNECT_START = 'CLOUD_CONNECT_START';
export const CLOUD_CONNECT_SUCCESS = 'CLOUD_CONNECT_SUCCESS';
export const CLOUD_CONNECT_FAIL = 'CLOUD_CONNECT_FAIL';

export const CLOUD_CONNECT_CHART_START = 'CLOUD_CONNECT_CHART_START';
export const CLOUD_CONNECT_CHART_SUCCESS = 'CLOUD_CONNECT_CHART_SUCCESS';
export const CLOUD_CONNECT_CHART_FAIL = 'CLOUD_CONNECT_CHART_FAIL';

export const CLOUD_CONNECT_INTERNAL_HOST_START = 'CLOUD_CONNECT_INTERNAL_HOST_START';
export const CLOUD_CONNECT_INTERNAL_HOST_SUCCESS = 'CLOUD_CONNECT_INTERNAL_HOST_SUCCESS';
export const CLOUD_CONNECT_INTERNAL_HOST_FAIL = 'CLOUD_CONNECT_INTERNAL_HOST_FAIL';

export const CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_START = 'CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_START';
export const CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_SUCCESS = 'CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_SUCCESS';
export const CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_FAIL = 'CLOUD_CONNECT_INTERNAL_TO_EXTERNAL_FAIL';

export const ADD_CLOUD_CONNECT_START = 'ADD_CLOUD_CONNECT_START';
export const ADD_CLOUD_CONNECT_SUCCESS = 'ADD_CLOUD_CONNECT_SUCCESS';
export const ADD_CLOUD_CONNECT_FAIL = 'ADD_CLOUD_CONNECT_FAIL';

export const EDIT_CLOUD_CONNECT_START = 'EDIT_CLOUD_CONNECT_START';
export const EDIT_CLOUD_CONNECT_SUCCESS = 'EDIT_CLOUD_CONNECT_SUCCESS';
export const EDIT_CLOUD_CONNECT_FAIL = 'EDIT_CLOUD_CONNECT_FAIL';


// ZOOM VIEW ACTIONS
export const MONITOR_INSTANCES_VM_INFO_START = 'MONITOR_INSTANCES_VM_INFO_START';
export const MONITOR_INSTANCES_VM_INFO_SUCCESS = 'MONITOR_INSTANCES_VM_INFO_SUCCESS';
export const MONITOR_INSTANCES_VM_INFO_FAIL = 'MONITOR_INSTANCES_VM_INFO_FAIL';

export const MONITOR_INSTANCES_START = 'MONITOR_INSTANCES_START';
export const MONITOR_INSTANCES_SUCCESS = 'MONITOR_INSTANCES_SUCCESS';
export const MONITOR_INSTANCES_FAIL = 'MONITOR_INSTANCES_FAIL';

export const MONITOR_SERVICES_START = 'MONITOR_SERVICES_START';
export const MONITOR_SERVICES_SUCCESS = 'MONITOR_SERVICES_SUCCESS';
export const MONITOR_SERVICES_FAIL = 'MONITOR_SERVICES_FAIL';

export const MONITOR_CPU_GRAPHS_START = 'MONITOR_CPU_GRAPHS_START';
export const MONITOR_CPU_GRAPHS_SUCCESS = 'MONITOR_CPU_GRAPHS_SUCCESS';
export const MONITOR_CPU_GRAPHS_FAIL = 'MONITOR_CPU_GRAPHS_FAIL';

export const MONITOR_RAM_GRAPHS_START = 'MONITOR_RAM_GRAPHS_START';
export const MONITOR_RAM_GRAPHS_SUCCESS = 'MONITOR_RAM_GRAPHS_SUCCESS';
export const MONITOR_RAM_GRAPHS_FAIL = 'MONITOR_RAM_GRAPHS_FAIL';

export const MONITOR_CPU_LOAD_GRAPHS_START = 'MONITOR_CPU_LOAD_GRAPHS_START';
export const MONITOR_CPU_LOAD_GRAPHS_SUCCESS = 'MONITOR_CPU_LOAD_GRAPHS_SUCCESS';
export const MONITOR_CPU_LOAD_GRAPHS_FAIL = 'MONITOR_CPU_LOAD_GRAPHS_FAIL';

export const MONITOR_HDD_GRAPHS_START = 'MONITOR_HDD_GRAPHS_START';
export const MONITOR_HDD_GRAPHS_SUCCESS = 'MONITOR_HDD_GRAPHS_SUCCESS';
export const MONITOR_HDD_GRAPHS_FAIL = 'MONITOR_HDD_GRAPHS_FAIL';

export const MONITOR_DISK_IO_GRAPHS_START = 'MONITOR_DISK_IO_GRAPHS_START';
export const MONITOR_DISK_IO_GRAPHS_SUCCESS = 'MONITOR_DISK_IO_GRAPHS_SUCCESS';
export const MONITOR_DISK_IO_GRAPHS_FAIL = 'MONITOR_DISK_IO_GRAPHS_FAIL';

export const MONITOR_INTERFACES_GRAPHS_START = 'MONITOR_INTERFACES_GRAPHS_START';
export const MONITOR_INTERFACES_GRAPHS_SUCCESS = 'MONITOR_INTERFACES_GRAPHS_SUCCESS';
export const MONITOR_INTERFACES_GRAPHS_FAIL = 'MONITOR_INTERFACES_GRAPHS_FAIL';

export const MONITOR_TCP_CONNECTIONS_GRAPHS_START = 'MONITOR_TCP_CONNECTIONS_GRAPHS_START';
export const MONITOR_TCP_CONNECTIONS_GRAPHS_SUCCESS = 'MONITOR_TCP_CONNECTIONS_GRAPHS_SUCCESS';
export const MONITOR_TCP_CONNECTIONS_GRAPHS_FAIL = 'MONITOR_TCP_CONNECTIONS_GRAPHS_FAIL';

export const MONITOR_NO_OF_THREADS_GRAPHS_START = 'MONITOR_NO_OF_THREADS_GRAPHS_START';
export const MONITOR_NO_OF_THREADS_GRAPHS_SUCCESS = 'MONITOR_NO_OF_THREADS_GRAPHS_SUCCESS';
export const MONITOR_NO_OF_THREADS_GRAPHS_FAIL = 'MONITOR_NO_OF_THREADS_GRAPHS_FAIL';

export const MONITOR_INTERNET_LINE_GRAPHS_START = 'MONITOR_INTERNET_LINE_GRAPHS_START';
export const MONITOR_INTERNET_LINE_GRAPHS_SUCCESS = 'MONITOR_INTERNET_LINE_GRAPHS_SUCCESS';
export const MONITOR_INTERNET_LINE_GRAPHS_FAIL = 'MONITOR_INTERNET_LINE_GRAPHS_FAIL';

export const MONITOR_EXTERNAL_IP_START = 'MONITOR_EXTERNAL_IP_START';
export const MONITOR_EXTERNAL_IP_SUCCESS = 'MONITOR_EXTERNAL_IP_SUCCESS';
export const MONITOR_EXTERNAL_IP_FAIL = 'MONITOR_EXTERNAL_IP_FAIL';

export const MONITOR_TOP_APPS_START = 'MONITOR_TOP_APPS_START';
export const MONITOR_TOP_APPS_SUCCESS = 'MONITOR_TOP_APPS_SUCCESS';
export const MONITOR_TOP_APPS_FAIL = 'MONITOR_TOP_APPS_FAIL';

export const MONITOR_GEO_TRAFFIC_START = 'MONITOR_GEO_TRAFFIC_START';
export const MONITOR_GEO_TRAFFIC_SUCCESS = 'MONITOR_GEO_TRAFFIC_SUCCESS';
export const MONITOR_GEO_TRAFFIC_FAIL = 'MONITOR_GEO_TRAFFIC_FAIL';

export const MONITOR_ISP_CONTRIBUTOR_START = 'MONITOR_ISP_CONTRIBUTOR_START';
export const MONITOR_ISP_CONTRIBUTOR_SUCCESS = 'MONITOR_ISP_CONTRIBUTOR_SUCCESS';
export const MONITOR_ISP_CONTRIBUTOR_FAIL = 'MONITOR_ISP_CONTRIBUTOR_FAIL';


export const MONITOR_TASKS_START = 'MONITOR_TASKS_START';
export const MONITOR_TASKS_SUCCESS = 'MONITOR_TASKS_SUCCESS';
export const MONITOR_TASKS_FAIL = 'MONITOR_TASKS_FAIL';

export const MONITOR_BACKUP_START = 'MONITOR_BACKUP_START';
export const MONITOR_BACKUP_SUCCESS = 'MONITOR_BACKUP_SUCCESS';
export const MONITOR_BACKUP_FAIL = 'MONITOR_BACKUP_FAIL';

// SETTINGS ACTIONS
export const GETTING_DAILY_REPORT_START = 'GETTING_DAILY_REPORT_START';
export const GETTING_DAILY_REPORT_SUCCESS = 'GETTING_DAILY_REPORT_SUCCESS';
export const GETTING_DAILY_REPORT_FAIL = 'GETTING_DAILY_REPORT_FAIL';

export const POSTING_DAILY_REPORT_START = 'POSTING_DAILY_REPORT_START';
export const POSTING_DAILY_REPORT_SUCCESS = 'POSTING_DAILY_REPORT_SUCCESS';
export const POSTING_DAILY_REPORT_FAIL = 'POSTING_DAILY_REPORT_FAIL';

export const POSTING_NOTIFICATIONS_START = 'POSTING_NOTIFICATIONS_START';
export const POSTING_NOTIFICATIONS_SUCCESS = 'POSTING_NOTIFICATIONS_SUCCESS';
export const POSTING_NOTIFICATIONS_FAIL = 'POSTING_NOTIFICATIONS_FAIL';


// BILLING ACTIONS 
export const BILLING_INVOICES_START = "BILLING_INVOICES_START";
export const BILLING_INVOICES_SUCCESS = "BILLING_INVOICES_SUCCESS";
export const BILLING_INVOICES_FAIL = "BILLING_INVOICES_FAIL";

export const BILLING_PAYMENT_HISTORY_START = "BILLING_PAYMENT_HISTORY_START";
export const BILLING_PAYMENT_HISTORY_SUCCESS = "BILLING_PAYMENT_HISTORY_SUCCESS";
export const BILLING_PAYMENT_HISTORY_FAIL = "BILLING_PAYMENT_HISTORY_FAIL";

export const PAYING_START = "BILLING_PAYING_START";
export const PAYING_SUCCESS = "BILLING_PAYING_SUCCESS";
export const PAYING_FAIL = "BILLING_PAYING_FAIL";

export const BILLING_BANDWIDTH_USAGE_START = "BILLING_BANDWIDTH_USAGE_START";
export const BILLING_BANDWIDTH_USAGE_SUCCESS = "BILLING_BANDWIDTH_USAGE_SUCCESS";
export const BILLING_BANDWIDTH_USAGE_FAIL = "BILLING_BANDWIDTH_USAGE_FAIL";


// REPORTS ACTIONS

// bandwidth
export const IP_DATA_START = 'IP_DATA_START';
export const IP_DATA_SUCCESS = 'IP_DATA_SUCCESS';
export const IP_DATA_FAIL = 'IP_DATA_FAIL';

// IP Tracking
export const IP_EXTERNAL_START = 'IP_EXTERNAL_START';
export const IP_EXTERNAL_SUCCESS = 'IP_EXTERNAL_SUCCESS';
export const IP_EXTERNAL_FAIL = 'IP_EXTERNAL_FAIL';

// Top Apps
export const IP_APPS_START = 'IP_APPS_START';
export const IP_APPS_SUCCESS = 'IP_APPS_SUCCESS';
export const IP_APPS_FAIL = 'IP_APPS_FAIL';

// Geo Traffic
export const IP_CITIES_START = 'IP_CITIES_START';
export const IP_CITIES_SUCCESS = 'IP_CITIES_SUCCESS';
export const IP_CITIES_FAIL = 'IP_CITIES_FAIL';

// ip report
export const IP_REPORT_DATA_START = 'IP_REPORT_DATA_START';
export const IP_REPORT_DATA_SUCCESS = 'IP_REPORT_DATA_SUCCESS';
export const IP_REPORT_DATA_FAIL = 'IP_REPORT_DATA_FAIL';

// USER PROFILE

export const FETCH_USER_DETAILS_START = 'FETCH_USER_DETAILS_START';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAIL = 'FETCH_USER_DETAILS_FAIL';

export const UPDATE_USER_PASSWORD_START = 'UPDATE_USER_PASSWORD_START';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';

export const UPDATE_USER_NAME_START = 'UPDATE_USER_NAME_START';
export const UPDATE_USER_NAME_SUCCESS = 'UPDATE_USER_NAME_SUCCESS';
export const UPDATE_USER_NAME_FAIL = 'UPDATE_USER_NAME_FAIL';


export const UPLOAD_USER_IMG_START = 'UPLOAD_USER_IMG_START';
export const UPLOAD_USER_IMG_SUCCESS = 'UPLOAD_USER_IMG_SUCCESS';
export const UPLOAD_USER_IMG_FAIL = 'UPLOAD_USER_IMG_FAIL';


export const SET_LOGIN_COC_PANEL_TYPE = 'SET_LOGIN_COC_PANEL_TYPE';


export const PROFILE_IMAGE_CHANGED = 'PROFILE_IMAGE_CHANGED';